/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.workers.Greeter;

import io.littlehorse.sdk.common.config.LHConfig;
import io.littlehorse.sdk.common.proto.LittleHorseGrpc.LittleHorseBlockingStub;
import io.littlehorse.sdk.wfsdk.WfRunVariable;
import io.littlehorse.sdk.wfsdk.Workflow;
import io.littlehorse.sdk.worker.LHTaskWorker;

public class App {
  

    public static void main(String[] args) {
        LHConfig config = new LHConfig();
        LittleHorseBlockingStub client = config.getBlockingStub();

        Greeter greeter = new Greeter();
        LHTaskWorker greetWorker = new LHTaskWorker(greeter, "greet", config);
        //Runtime.getRuntime().addShutdownHook(new Thread(greetWorker::close));
        greetWorker.registerTaskDef();


        Workflow wfSpecGenerator = Workflow.newWorkflow("greet-workflow", wf->{
            WfRunVariable name = wf.declareStr("name").required();

            wf.execute("greet", name);
            
            wf.execute("greet", "steve");
            wf.execute("greet", "joe");

          //  wf.doIf(name.isEqualTo("obi-wan"), ifHandler ->{
          //  some other logic
          //  })

        });

        wfSpecGenerator.registerWfSpec(config);
        //greetWorker.start();

    }
}
