plugins {
    id 'application'
}

group = 'io.littlehorse.examples'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.littlehorse:littlehorse-client:1.2.1'
    implementation 'org.slf4j:slf4j-api:2.0.7'
    runtimeOnly 'org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add('-parameters')
}

application {
    mainClass = 'io.littlehorse.examples.QuickstartApplication'
}
