/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.workers.Greeter;

import io.littlehorse.sdk.common.config.LHConfig;
import io.littlehorse.sdk.worker.LHTaskWorker;

public class App {

    public static void main(String[] args) {
        LHConfig config = new LHConfig();

        Greeter greeter = new Greeter();
        LHTaskWorker greeterWorker = new LHTaskWorker(greeter, "greet" , config);
        greeterWorker.registerTaskDef();

        

    }
}
