plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.littlehorse.client
    runtimeOnly 'org.slf4j:slf4j-simple:2.0.17'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add('-parameters')
}

application {
    mainClass = 'io.littlehorse.docs.usertasks.Main'
}