/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // takes in a couple command line arguments, eg:
        // - no arguments --> register the workflow and start task workers
        // - register-external-event-def --> register the externalEventDef with GRPC
        // - post-event --> uses grpc to post an externalEvent
    }
}
