/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.Assert.assertNotNull;
import org.junit.Test;

public class AppTest {
    @Test
    public void appClassLoads() {
        App classUnderTest = new App();
        assertNotNull("app should be instantiable", classUnderTest);
    }
}
