plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.littlehorse.client
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add('-parameters')
}

application {
    mainClass = 'io.littlehorse.examples.TaskFailuresExample'
}
